version: "3"
services:
  tachiload:
    build: .
    restart: unless-stopped
    volumes:
      - /app/docker/data/tachiload/config.json:/app/config.json
      - /nas/Mangas:/app/downloads
    environment: 
      TACHILOAD_CRON: "0 */6 * * *"