FROM openjdk:8-jdk-buster AS builder

WORKDIR /app
RUN apt-get update && apt-get install -y python3 git \
     libwoff1 libopus0 libwebp6 libwebpdemux2 libenchant1c2a libgudev-1.0-0 libsecret-1-0 libhyphen0 libgdk-pixbuf2.0-0 libegl1 libnotify4 libxslt1.1 libevent-2.1-6 libgles2 libvpx5 libxcomposite1 libatk1.0-0 libatk-bridge2.0-0 libepoxy0 libgtk-3-0 libharfbuzz-icu0 libnss3 libxss1 libasound2 fonts-noto-color-emoji libxtst6 libdbus-glib-1-2 libxt6 xvfb
RUN git clone --depth 1 https://github.com/tachiyomiorg/tachiyomi-extensions /tmp/tachiyomi-extensions

ADD . /app
RUN rm -rf /app/app/src/main/kotlin/tachiload/extension \
    && mkdir -p /app/app/src/main/kotlin/tachiload/extension \
    && mv /tmp/tachiyomi-extensions/src/* /app/app/src/main/kotlin/tachiload/extension \
    && cd /app/scripts \
    && python3 compat_init.py \
    && python3 prepare.py \
    && python3 compat_deps.py \
    && python3 build.py \
    && python3 compat_build.py \
    && python3 test.py \
    && python3 compat_export.py
