FROM openjdk:8-jdk-buster AS builder

WORKDIR /app
RUN apt-get update && apt-get install -y python3 git
RUN git clone --depth 1 https://github.com/tachiyomiorg/tachiyomi-extensions /tmp/tachiyomi-extensions
ADD . /app
RUN rm -rf /app/app/src/main/kotlin/tachiload/extension \
    && mkdir -p /app/app/src/main/kotlin/tachiload/extension \
    && mv /tmp/tachiyomi-extensions/src/* /app/app/src/main/kotlin/tachiload/extension \
    && chmod +x /app/gradlew \
    && cd /app/scripts \
    && python3 compat.py \
    && python3 prepare.py \
    && python3 build.py \
    && python3 compat_export.py
