version: "3"
services:
  tachiload:
    command: --cron "0 */6 * * *"
    build: .
    restart: unless-stopped
    volumes:
      - /app/docker/data/tachiload/config.json:/app/config.json
      - /nas/Mangas:/app/downloads
